// <auto-generated />
using IMS.Plugins.EFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMS.Plugins.EFCore.Migrations
{
    [DbContext(typeof(IMSDbContext))]
    [Migration("20260416045722_AddCategoriesUnicodeRu")]
    partial class AddCategoriesUnicodeRu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Material_category", (string)null);
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.MaterialNomenclature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CrossSection")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cross_section");

                    b.Property<decimal>("CurrentStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("Current_stock");

                    b.Property<string>("Gost")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GOST");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("Type_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("м")
                        .HasColumnName("Unit");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Material_nomenclature_SKU")
                        .HasFilter("[SKU] IS NOT NULL");

                    b.HasIndex("TypeId", "Name")
                        .HasDatabaseName("IX_Material_nomenclature_Type_Name");

                    b.ToTable("Material_nomenclature", (string)null);
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Subcategory_id");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Material_type", (string)null);
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Material_subcategory", (string)null);
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("First_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.ToTable("User_account", (string)null);
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.MaterialNomenclature", b =>
                {
                    b.HasOne("IMS.CoreBusiness.Entities.Materials.MaterialType", "Type")
                        .WithMany("Nomenclatures")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.MaterialType", b =>
                {
                    b.HasOne("IMS.CoreBusiness.Entities.Materials.Subcategory", "Subcategory")
                        .WithMany("Types")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.Subcategory", b =>
                {
                    b.HasOne("IMS.CoreBusiness.Entities.Materials.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.MaterialType", b =>
                {
                    b.Navigation("Nomenclatures");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Entities.Materials.Subcategory", b =>
                {
                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
